---
- hosts: web
  vars:
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_env: test
    db_host: rds-db.cxvytcpxrmgm.us-west-2.rds.amazonaws.com:3306
    db_database: curriculum
    db_username: jzd914
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
    ansible_ssh_private_key_file: ~/.ssh/cit360.pem
  vars_files:
    - secrets.yml 
  tasks:
#      name: Change SELinux to permissive
#      become: yes
#      lineinfile: dest=/etc/sysconfig/selinux regexp="^SELINUX=" line="SELINUX=permissive"
      
#    - name: Run setenforce
#      become: yes
#      command: setenforce

    - name: Install epel-release
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: Install PHP files
      become: yes
      shell: yes | yum install php54 php54-fpm php54-ldap php54-mbstring php54-mcrypt php54-pdo php54-mysqlnd

    - name: install nginx/php packages
      become: yes
      yum: name=nginx update_cache=yes state=present
      register: nginx_install

    - name: Download get composer to remote location
      become: yes
      shell: get_url -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    - name: copy nginx
      become: yes
      copy: src=web/nginx.conf dest=/etc/nginx/nginx.conf mode=0644
      register: nginx_conf

    - name: Templete vhost
      become: yes
      template: src=web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

    - name: Templete php.ini.j2
      become: true
      template: src=web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf
#configure php

    - name: Copy file to remote location
      become: yes
      copy: src=web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: Bounce nginx
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: Bounce php-fpm
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: Edit directory 
      become: yes
      file: path="{{ service_dir }}" state=directory

    - name: Unarachive file
      become: yes
      unarchive: src=web/{{ service_name }}.tgz dest="{{ service_dir }}" mode=0755

    - name: Execute chdir
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}

    - name: Execute Chmod
      become: yes
      shell: chdir="{{ service_dir }}" mode 0777
#      command: chmod -R 0777 storage chdir="{{ service_dir }}"

    - name: Execute chown
      become: yes
      file: path="{{ service_dir }}" owner=nginx state=directory recurse=yes
#      command: chown -R nginx:nginx . chdir="{{ service_dir }}"

    - name: move file
      become: yes
      template: src=web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx


